//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public string Date_priemki { get; set; }
        public int Tabel_number { get; set; }
        public int Id_car { get; set; }
        public string Date_get { get; set; }
        public string Car_trouble { get; set; }
        public string Job_description { get; set; }
        public string Work_time { get; set; }
    
        public virtual CarTable CarTable { get; set; }
        public virtual MechanicTable MechanicTable { get; set; }
    }
}
